parameters:
#    ciudad_tigre_anunciante.example.class: CiudadTigre\AnuncianteBundle\Example

services:
#    ciudad_tigre_anunciante.example:
#        class: %ciudad_tigre_anunciante.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
