parameters:
#    anunciante.example.class: CiudadTigre\AnuncianteBundle\Example

services:
#    anunciante.example:
#        class: %anunciante.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
