<?php
namespace CiudadTigre\AnuncianteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AdministradorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdministradorRepository extends EntityRepository
{
    public function findAdministrador()
    {
        $em = $this->getEntityManager();
        
        $consulta = $em->createQuery('
            SELECT a
              FROM CiudadTigreAnuncianteBundle:Administrador a');
        
        return $consulta->getOneOrNullResult();
    }

}
