<?php
namespace CiudadTigre\AnuncianteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AnuncianteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnuncianteRepository extends EntityRepository
{
    public function queryAnunciantesByNombre($nombre)
    {
        $em = $this->getEntityManager();
        $consulta = $em->createQuery('
                SELECT a
                  FROM CiudadTigreAnuncianteBundle:Anunciante a
                 WHERE a.nombre LIKE :nombre');
        
        $consulta->setParameter('nombre', '%'.$nombre.'%');
        
        return $consulta;
    }
    
    public function getAnunciantesByNombre($nombre)
    {
        $em = $this->getEntityManager();
        
        $consulta = $em->createQuery('
            SELECT a
              FROM CiudadTigreAnuncianteBundle:Anunciante a
             WHERE a.nombre LIKE :nombre
               AND a.habilitado = TRUE');
        
        $consulta->setParameter('nombre', '%'.$nombre.'%');
        
        return $consulta->getResult();
    }
    
    public function getAnunciantesLetraInicial($letra)
    {
        $em = $this->getEntityManager();
        
        $consulta = $em->createQuery('
            SELECT a
              FROM CiudadTigreAnuncianteBundle:Anunciante a
             WHERE a.nombre LIKE :nombre
          ORDER BY a.nombre ASC');
        
        $consulta->setParameter('nombre', $letra.'%');
        
        return $consulta->getResult();
    }
    
    public function queryTodasLosAnunciantes()
    {
        $em = $this->getEntityManager();
        $consulta = $em->createQuery('
                SELECT a FROM CiudadTigreAnuncianteBundle:Anunciante a
              ORDER BY a.nombre ASC');
        
        return $consulta;
    }
    
    public function findTodasLosAnunciantes()
    {
        return $this->queryTodasLosAnunciantes()->getResult();
    }
    
    public function findAnunciantesSubcategoria($subcategoria_id)
    {
        $em = $this->getEntityManager();
        
        $consulta = $em->createQuery('
            SELECT a
              FROM CiudadTigreAnuncianteBundle:Anunciante a
             WHERE a.subcategoria = :id
               AND a.habilitado = 1
          ORDER BY a.nombre ASC');
        
        $consulta->setParameter('id', $subcategoria_id);
        
        return $consulta->getResult();
    }
    
    public function updateHits($id)
    {
        $em = $this->getEntityManager();
        
        $consulta = $em->createQuery('
             UPDATE CiudadTigreAnuncianteBundle:Anunciante a
                SET a.hits = a.hits + 1
              WHERE a.id = :id');
        
        $consulta->setParameter('id', $id);
        
        return $consulta->execute();
    }

}
