<?php
namespace CiudadTigre\AnuncianteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriaRepository extends EntityRepository
{
    public function findCategorias()
    {
        $em = $this->getEntityManager();
        
        $consulta = $em->createQuery('
                SELECT c, s
                  FROM CiudadTigreAnuncianteBundle:Subcategoria c
                  JOIN c.categoria s');
        
        return $consulta->getResult();
    }
}
