<?php

namespace CiudadTigre\AnuncianteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SubcategoriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubcategoriaRepository extends EntityRepository
{
    public function findAll()
    {
        return $this->findBy(array(), array('nombre' => 'ASC'));
    }
    
    public function getByCategoriasOrderBy($id)
    {
        $em = $this->getEntityManager();
        
        $consulta = $em->createQuery('
            SELECT a
              FROM CiudadTigreAnuncianteBundle:Subcategoria a
             WHERE a.categoria = :id
          ORDER BY a.nombre');
        
        $consulta->setParameter('id', $id);
        
        return $consulta->getResult();
    }
}
